### ISSUE TITLE
module initialization order - readinitfiles and microphysics

### ISSUE THREAD

**Issue by fjansson** [dalesteam/dales#49]
Commit 4f35105f18378 in version 4.2.1 changes the initialization order to
``` 
 call initmicrophysics
 call readinitfiles 
```
in modstartup.f90, line ~292.
This change breaks the simpleice2 microphysics, which needs rhobf profiles in its initialization routine to calculate some lookup tables.
If this order is necessary (why?), I can adapt the simpleice2 scheme, and calculate the lookup tables on each call - performance should not suffer much.

**Comment by huugouwersloot** [comment]
This commit was a revert to the old situation, because the previously changed order caused bugs (it had something to do with scalars initialization which came to light, because chemistry stopped working properly). Some cases at WUR were going wrong because of this. 
The order after this commit should be maintained and indeed a workaround for the new scheme should be applied
