### ISSUE TITLE
GOAMAZON14 case does not run

### ISSUE THREAD

**Issue by fjansson** [dalesteam/dales#50]
```
 WARNING ::: There is no CO2 defined in the chemistry scheme
 WARNING ::: Scalar 1 might be considered to be CO2 
STOP ERROR: Problem in namoptions NAMSURFACE - AGS
```
printed at line 1822 in modsurface.f90.
This is with the branch to4.3_Fredrik, where the chemistry and surface code is unchanged since Dales 4.2.1.

Scalar 21 is CO2 according to chem.inp.047 and scalar.inp.047.

**Comment by huugouwersloot** [comment]
This is due to incorrect settings in the namoptions file. If 'lastchem' is set to a value lower than the amount of scalars in the  numerical experiment, the scalars that do not belong to the first <lastchem> amount of scalars are not recognized as chemical species.
If the last (or all) scalars are chemical species, as is common, it is actually safer to remove the 'lastchem' entry from the numerical experiment namoptions file. 

The bug is therefore in the case input files; rather than in the DALES code.
Note that this bug appeared before; in the experiments that were uploaded here, it was not yet identified and an hard coded temporary override was applied. Later tests confirmed that solving the issue with lastchem negated the need for that hard coded temporary override.

**Comment by fjansson** [comment]
setting lastchem = 21 in the namelists fixed this.
